symfony_of_grace_battle_homepage:
    pattern:  /
    defaults: { _controller: SymfonyOfGraceBattleBundle:Default:index }
symfony_of_grace_battle_contactpage:
    pattern:  /contact
    defaults: { _controller: SymfonyOfGraceBattleBundle:Default:contact }
